name: store-services

version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  config-server-service:
    image: evanellenstore/config-server-service:latest
    container_name: config-server-service
    ports:
      - "8850:8850"
    restart: always
    depends_on:
      - mysql

  eureka-server-service:
    image: evanellenstore/eureka-server-service:latest
    container_name: eureka-server-service
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - config-server-service

  cloud-gateway-service:
    image: evanellenstore/cloud-gateway-service:latest
    container_name: cloud-gateway-service
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - config-server-service
      - eureka-server-service
    environment:
      CONFIG_SERVER_URL: configserver:http://host.docker.internal:8850
      EUREKA_URL: http://eureka-server-service:8761/eureka
      SERVICE_URL1: http://host.docker.internal:2011
      SERVICE_URL2: http://host.docker.internal:2010

  #inventory-service:
  #  image: evanellenstore/inventory-service:latest
  #  container_name: inventory-service
  #  ports:
  #    - "2011:2011"
  #  restart: always
  #  depends_on:
  #    - mysql
  #    - config-server-service
  #    - eureka-server-service
  #  environment:
  #    DB_URL: jdbc:mysql://mysql:3306/store_db
  #    DB_USERNAME: root
  #    DB_PASSWORD: root
  #    CONFIG_SERVER_URL: configserver:http://config-server-service:8850
  #    EUREKA_URL: http://eureka-server-service:9091/eureka

volumes:
  mysql-data:
