server:
  port: 8850
  

spring:
  application:
    name: config-cloud-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/evanellenstore/config-file-repo
          username: evanellenstore
          password: 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
          default-label: main
          clone-on-start: true
