server:
  port: 8850

spring:
  application:
    name: config-cloud-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Divyanshverma2/config-repo
          username: Divyanshverma2
          password: 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
          default-label: main
          clone-on-start: true
